Repository codehaus-plexus/modello, pull requests merged in 2024-02, with the labels that each got.

#413 Use generic in Xpp3Reader for JDK 5+
  modello-plugins/modello-plugin-xpp3/src/main/java/org/codehaus/modello/plugin/xpp3/Xpp3ReaderGenerator.java
Labels: enhancement

#411 Use mailing lists from parent - current lists in project are not available any more
  pom.xml
Labels: maintenance

#414 Parse javadoc tags in xdoc generator (only @since is supported atm)
  modello-plugins/modello-plugin-xdoc/pom.xml
  modello-plugins/modello-plugin-xdoc/src/main/java/org/codehaus/modello/plugin/xdoc/XdocGenerator.java
  modello-plugins/modello-plugin-xdoc/src/test/java/org/codehaus/modello/plugin/xdoc/XdocGeneratorTest.java
  modello-plugins/modello-plugin-xdoc/src/test/resources/html4.expected.xml
  modello-plugins/modello-plugin-xdoc/src/test/resources/html4.mdo
Labels: enhancement

#422 Revert snakeyaml to 1.33 (as 2.x is not fully compatible with 1.x)
  modello-plugins/modello-plugin-snakeyaml/pom.xml
Labels: bug, dependencies

#425 Make generated code - Java 8 based by default
  modello-plugins/modello-plugin-dom4j/src/test/java/org/codehaus/modello/plugin/dom4j/FeaturesDom4jGeneratorTest.java
  modello-plugins/modello-plugin-jackson/src/main/java/org/codehaus/modello/plugin/jackson/JacksonReaderGenerator.java
  modello-plugins/modello-plugin-jackson/src/main/java/org/codehaus/modello/plugin/jackson/JacksonWriterGenerator.java
  modello-plugins/modello-plugin-jackson/src/test/java/org/codehaus/modello/plugin/jackson/JacksonGeneratorTest.java
  modello-plugins/modello-plugin-java/src/main/java/org/codehaus/modello/plugin/java/AbstractJavaModelloGenerator.java
  modello-plugins/modello-plugin-java/src/main/java/org/codehaus/modello/plugin/java/JavaModelloGenerator.java
  modello-plugins/modello-plugin-java/src/main/java/org/codehaus/modello/plugin/java/javasource/JArrayType.java
  modello-plugins/modello-plugin-java/src/main/java/org/codehaus/modello/plugin/java/javasource/JCollectionType.java
  modello-plugins/modello-plugin-java/src/main/java/org/codehaus/modello/plugin/java/javasource/JComponentizedType.java
  modello-plugins/modello-plugin-java/src/main/java/org/codehaus/modello/plugin/java/javasource/JMapType.java
  modello-plugins/modello-plugin-java/src/test/java/org/codehaus/modello/plugin/java/AnnotationsJava4GeneratorTest.java
  modello-plugins/modello-plugin-java/src/test/java/org/codehaus/modello/plugin/java/AnnotationsJavaGeneratorTest.java
  modello-plugins/modello-plugin-java/src/test/java/org/codehaus/modello/plugin/java/FeaturesJava5GeneratorTest.java
  modello-plugins/modello-plugin-java/src/test/java/org/codehaus/modello/plugin/java/InterfaceAssociationTest.java
  modello-plugins/modello-plugin-java/src/test/java/org/codehaus/modello/plugin/java/LocationsJavaGeneratorTest.java
  modello-plugins/modello-plugin-java/src/test/java/org/codehaus/modello/plugin/java/javasource/JMapTypeTestCase.java
  modello-plugins/modello-plugin-java/src/test/java/org/codehaus/modello/plugin/java/javasource/JavaSourceTest.java
  modello-plugins/modello-plugin-jdom/src/main/java/org/codehaus/modello/plugin/jdom/JDOMWriterGenerator.java
  modello-plugins/modello-plugin-sax/src/main/java/org/codehaus/modello/plugin/sax/SaxWriterGenerator.java
  modello-plugins/modello-plugin-snakeyaml/src/main/java/org/codehaus/modello/plugin/snakeyaml/SnakeYamlReaderGenerator.java
  modello-plugins/modello-plugin-snakeyaml/src/main/java/org/codehaus/modello/plugin/snakeyaml/SnakeYamlWriterGenerator.java
  modello-plugins/modello-plugin-stax/src/test/java/org/codehaus/modello/generator/xml/stax/BooleanTypeStaxGeneratorTest.java
  modello-plugins/modello-plugin-stax/src/test/java/org/codehaus/modello/generator/xml/stax/FeaturesStaxDomGeneratorTest.java
  modello-plugins/modello-plugin-stax/src/test/java/org/codehaus/modello/generator/xml/stax/FeaturesStaxGeneratorTest.java
  modello-plugins/modello-plugin-xpp3/src/main/java/org/codehaus/modello/plugin/xpp3/Xpp3ReaderGenerator.java
  modello-plugins/modello-plugin-xpp3/src/test/java/org/codehaus/modello/generator/xml/xpp3/BooleanTypeXpp3GeneratorTest.java
  modello-plugins/modello-plugin-xpp3/src/test/java/org/codehaus/modello/generator/xml/xpp3/FeaturesXpp3DomGeneratorTest.java
  modello-plugins/modello-plugin-xpp3/src/test/java/org/codehaus/modello/generator/xml/xpp3/FeaturesXpp3GeneratorTest.java
  modello-plugins/modello-plugin-xpp3/src/test/java/org/codehaus/modello/generator/xml/xpp3/LocationsSourceXpp3GeneratorTest.java
  modello-plugins/modello-plugin-xpp3/src/test/java/org/codehaus/modello/generator/xml/xpp3/LocationsXpp3GeneratorTest.java
  modello-plugins/modello-plugin-xpp3/src/test/java/org/codehaus/modello/generator/xml/xpp3/StandaloneReadXpp3GeneratorTest.java
  modello-plugins/modello-plugin-xpp3/src/test/java/org/codehaus/modello/generator/xml/xpp3/Xpp3GeneratorTest.java
  modello-test/src/main/java/org/codehaus/modello/AbstractModelloGeneratorTest.java
  modello-test/src/main/java/org/codehaus/modello/AbstractModelloJavaGeneratorTest.java
Labels: enhancement
